import { Inter } from 'next/font/google';
import Provider from './lib/provider';
import Navbar from '@/app/components/Navbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider attribute="class" defaultTheme="system">
          <Navbar/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
