import { Inter } from 'next/font/google';
import Provider from './lib/provider';
import './globals.css'
import './polyfllls'
import Header from './components/header';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
